spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false   # replace for spring.cloud.gateway.discovery.locator.enabled
              lowerCaseServiceId: true
          httpclient:
            connect-timeout: 1000
            response-timeout: 10s
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:7080/realms/master/protocol/openid-connect/certs"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
#      enabled: true

  info:
    env:
      enabled: true
  metrics:  # group the metrics under application name gatewayserver
    tags:
      application: ${spring.application.name}

info:   # info for Eureka Dashboard, which is exposed as actuator endpoint, which we are allowing by management.info.env.enabled
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:   # can be replaced with our name in filters definition if we want different settings for different filters
      sliding-window-size: 10   # monitor at least 10 calls before making a decision  # slidingWindowSize is also allowed
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50  # 50% failure rate
      waitDurationInOpenState: 10000  # wait 10 seconds in open state
