build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "Carter Doe - Developer"
    email: "carter@eazybank.com"
  onCallSupport:
    - (555) 555-2234
    - (555) 523-2345
