build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank loans related to QA APIs"
  contactDetails:
    name: "Loaner Ray - QA lead"
    email: "loaner@eazybank.com"
  onCallSupport:
    - (777) 265-4765
    - (777) 734-9371
