server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
#    active: native  # to run in native mode. We do it always when using classpath approach.
    active: git
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/eazybytes/eazybytes-config.git
          uri: https://github.com/jjasonek/microservices-eazybytes-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native: # because we have activated the native profile
#          search-locations: "classpath:/config"
#          search-locations: "file:///C://Training//Microservices//section6//v2-spring-cloud-config//configserver//src//main//resources//config"

management:   # to see in browser http://localhost:8071/actuator
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics: # group the metrics under application name configserver
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
